### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rb26** [mateusz-matela/djvu-html5#12] opened 2017-12-12 14:47 UTC
bonjour
I have this error with firefox 57.0.1 (64 bits):

Error: com.google.gwt.useragent.client.UserAgentAsserter$UserAgentAssertionError: Possible problem with your *.gwt.xml module file. The compile time user.agent value (safari) does not match the runtime user.agent value (gecko1_8). Expect more errors.

81EB501BD7AB47786C30D3175CE1EA2B.cache.js:826:3636
rb

**Comment by mateusz-matela** [comment] 2017-12-12 20:57
Thanks for the report.
I've seen this error and it doesn't cause actual problems with displaying DjVu. It's related to the limited support for webworkers in GWT, but it's not something to be concerned about.

I'm closing the issue. If you do experience a problem, it may be caused by something else - in that case please reopen and provide a sample DjVu document.

**Closed as completed by mateusz-matela** 2017-12-12 20:57 UTC
